const skills = [
    'Next.js',
    'React',
    'React Native',
    'Redux',
    'Redux-Toolkit',
    'MobX',
    'Typescript',
    'JavaScript',
    'Node.js',
    'MongoDB',
    'Express',
    'SQL',
    'jQuery',
    'Cypress',
    'Jest',
    'React Testing Library',
    'Ant Design',
    'Material-UI',
    'Styled Components',
    'CSS',
    'LESS',
    'SASS',
    'Stylus',
    'HTML',
    'REST',
    'Algorithms & Data Structures'
];

export default skills;
